server {
  listen 80;

  location / {
    proxy_pass http://portfolio:3000;
  }

  location /monitoring/ {
    proxy_pass http://monitoring:3001/;
  }

  location /api/ {
    proxy_pass http://api:8000/api/;
  }
}

